experiment:
  total_epochs: 20
  patience: 4

hyperparameters:
  lr_start: 0.0007125891
  weight_decay: 0.0000282426
  lr_end: 0.0000007368
  numberOfLayers: 3
  embed_size: 188
  hidden_size: 1117

runtime:
  device: "cuda"  # Set this to "cpu" if you want to run on CPU
  num_workers: 8
  batch_size: 256
  shuffle: True

seeds:
  numpy_seed: 423455335
  torch_seed: 423455335

data:
  min_freq: 4
  context_size: 10
  training_data_corpus_path: '../rawWikiText2/wiki.train.txt'
  validation_data_corpus_path: '../rawWikiText2/wiki.valid.txt'
  test_data_corpus_path: '../rawWikiText2/wiki.test.txt'
